#pragma config(Sensor, in1,    lineFollower1,  sensorLineFollower)
#pragma config(Sensor, in2,    lineFollower2,  sensorLineFollower)
#pragma config(Sensor, in3,    lineFollower3,  sensorLineFollower)
#pragma config(Sensor, in4,    lineFollower4,  sensorLineFollower)
#pragma config(Sensor, in5,    lineFollower5,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  frontSonar,     sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  backSonar,      sensorSONAR_cm)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           frontLeftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           backServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: thig
  Team Members: person
  Date: date
  Section:


  Task Description:


  Pseudocode:

*/
void startAllMotors();
void startAllMotors() {
	startMotor(backLeftMotor, 50);
	startMotor(backRightMotor, 50);
	startMotor(frontLeftMotor, 50);
	startMotor(frontRightMotor, 50);
}

void startFrontMotors(int value);
void startFrontMotors(int value) {
	startMotor(frontLeftMotor, value);
	startMotor(frontRightMotor, value);
}

void turnSlightLeft(float time);
void turnSlightLeft(float time) {
	setServo(frontServo, -45);
	setServo(backServo, 0);
	wait(time);
}

void turnSharpLeft(float time);
void turnSharpLeft(float time) {
	setServo(frontServo, -90);
	setServo(backServo, 0);
	wait(time);
}

void turnStraight();
void turnStraight() {
	setServo(frontServo, 0);
	setServo(backServo, 0);
}

void turnSlightRight(float time);
void turnSlightRight(float time) {
	setServo(frontServo, 45);
	setServo(backServo, -30);
	wait(time);
}

void turnSharpRight(float time);
void turnSharpRight(float time) {
	setServo(frontServo, 90);
	setServo(backServo, 0);
	wait(time);
}

void leftToRightTurn(float time);
void leftToRightTurn(float time) {
	turnStraight();
	startFrontMotors(125);
	turnSlightRight(0.5);
	wait(time);
	turnSharpRight(time*1.5);
}

task main() {                                     //Program begins, insert code within curly braces
	startAllMotors();
	turnLEDOff(led);
	while (true) {
		if (SensorValue(lineFollower1) > 2750) {
			turnSlightLeft(1);
			turnLEDOn(led);
		}
		if (SensorValue(lineFollower2) > 2750) {
			turnSlightLeft(0.5);
			turnLEDOn(led);
		}
		if (SensorValue(lineFollower3) > 2750) {
			turnStraight();
			turnLEDOn(led);
		}
		if (SensorValue(lineFollower4) > 2750) {
			turnSlightRight(0.5);
			turnLEDOn(led);
		}
		if (SensorValue(lineFollower5) > 2750) {
			turnSlightRight(1);
			turnLEDOn(led);
		}
	}


}
